tasks:
  - name: terraform
    before: |
      source ./bin/install_terrafrom.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli.sh
  - name: generate tfrc token file
    before: |
      source ./bin/generate_tfrc_credentials.sh
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
